fix(compile): fix modules filtering

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -4,6 +4,7 @@ basedir="$( cd -P "$( dirname "$0" )" && pwd )"
 
 # Set errors
 set -e
+set -o pipefail
 
 # Configure directories
 BUILD_DIR=$1
@@ -11,8 +12,9 @@ CACHE_DIR=$2
 ENV_DIR=$3
 
 export APACHE_DIR="${APACHE_DIR:-$BUILD_DIR/vendor/apache2}"
+export APT_FILE_MANIFEST="Aptfile.apache"
 
-echo "apache2" >> "$BUILD_DIR/Aptfile"
+echo "apache2" >> "$BUILD_DIR/${APT_FILE_MANIFEST}"
 
 
 apt_deps_buildpack_dir=$(mktemp apt_buildpack_XXXX)
@@ -23,27 +25,36 @@ rm "$apt_deps_buildpack_dir"
 APT_BUILDPACK_URL="${APT_BUILDPACK_URL:-https://github.com/Scalingo/apt-buildpack}"
 git clone --depth=1 "$APT_BUILDPACK_URL" "$apt_deps_buildpack_dir"
 
+# We first install Apache alone:
 "${apt_deps_buildpack_dir}/bin/compile" "$BUILD_DIR" "$CACHE_DIR" "$ENV_DIR"
 
 
+# Then we have to filter out the list of modules the user requires.
+# Some are shipped with the Apache package, we don't want to try to install
+# them (it would make the buildpack fail).
 
+# Reset APT_FILE_MANIFEST so we don't re-install Apache:
+rm "${APT_FILE_MANIFEST}"
+
+# Build the list of modules to install:
 if [ -f "${BUILD_DIR}/.apache-mods" ] ; then
   grep -E '^[a-z-]+$' < "${BUILD_DIR}/.apache-mods" | while IFS= read -r apache_mod ; do
     apache_mod_filename="mod_$( echo "${apache_mod}" | tr "-" "_" ).so"
-    ls "${BUILD_DIR}/.apt/usr/lib/apache2/modules" \
-        | grep --quiet "${apache_mod_filename}"
+    install_mod="$( ls "${BUILD_DIR}/.apt/usr/lib/apache2/modules/" \
+                    | { grep --count "${apache_mod_filename}" || true; } )"
 
-    # if the previous grep doesn't find a result, we have to install the module
-    if [ ${?} -ne 0 ]; then
-        echo "libapache2-mod-${apache_mod}" >> "$BUILD_DIR/Aptfile"
+    # If the module isn't shipped by default, let's install it:
+    if [ ${install_mod} -eq 0 ]; then
+        echo "libapache2-mod-${apache_mod}" >> "$BUILD_DIR/${APT_FILE_MANIFEST}"
     fi
 
   done
 fi
 
-# 
-# 
-# 
+# We finally have to call the apt-buildpack again, this time to install the
+# missing Apache modules that we just filtered out.
+# At this point, if the module can't be found, it means it's neither a default
+# module nor an installable one. And the buildpack will fail.
 "${apt_deps_buildpack_dir}/bin/compile" "$BUILD_DIR" "$CACHE_DIR" "$ENV_DIR"
 
 rm -r "$apt_deps_buildpack_dir"
